### ISSUE TITLE
Phone is basically bricked

### ISSUE THREAD

**Issue by AdamAtomus** [reviveMC74/reviveMC74#16]
This phone is probably a lost cause but, i was wondering if there is any way i could get a recovery zip from clockworkmod to recover my device cause I basically went into this without a backup and no knowledge and wiped shit and ended up breaking it.
TLDR; i need someones recovery zip.

**Comment by qwery26** [comment]
How bricked are we talking about?   You can get the clockwork recovery image we use from the installFiles directory of this repo.

I assume you can't get into recovery mode.   Can you get into fastboot mode?  (Using the same procedure as getting into recovery mode except you hold down the 'Vol Down' button rather than the 'Mute' button.   Then use 'fastboot devices' rather than 'adb devices' to see if you can talk to the device.

Real 'bricking' would imply that the screen backlight does not some on and the vibrator 'grunt' doesn't happen.  Is that it?

Did this happen using reviveMC74.py?   Could you send the reviveMC74.log file so we can see what happened?

**Comment by AdamAtomus** [comment]
I can get into clockworkmod but the device will not boot anymore. and i did not make a backup using clockwork so im stuck.

**Comment by AdamAtomus** [comment]
Yes I can use adb and stuff but I no longer have a OS on it cause I somehow managed to mess that up, thats why I need a "backup / restore" file, this happened when I ran the script on linux after failing countless times on windows... I have a new phone coming in but I was hoping I could get a backup off of someone before then.

**Comment by AdamAtomus** [comment]
I managed to get an image from someone else, thanks for the help though.
